### ISSUE TITLE
Warning PR1014 / Generic routing resource will be used to clock signal

### ISSUE THREAD

**Issue by Semnodime** [sipeed/TangMega-138KPro-example#9]
# `key_led.gprj`

Warnings:
 - `TA1123`
 - `PR1014`

```
Running placement......
[10%] Placement Phase 0 completed
[20%] Placement Phase 1 completed
[30%] Placement Phase 2 completed
WARN  (TA1123) : the clock "osc_clk"'s frequency does not match internal_osc_inst/osc_inst/OSCOUT's 
[50%] Placement Phase 3 completed
Running routing......
[60%] Routing Phase 0 completed
[70%] Routing Phase 1 completed
[80%] Routing Phase 2 completed
WARN  (PR1014) : Generic routing resource will be used to clock signal 'sys_clk_d' by the specified constraint. And then it may lead to the excessive delay or skew
[90%] Routing Phase 3 completed
```

**Comment by kyonmiriam** [comment]
Hi
- For the **WARN  (TA1123)**, it is just a bug for GOWIN IDE. Due to decimal precision issues in **Timing Constraints Editor**, 70MHz will finally constrained to 69.9999MHz. However 70MHz≠ 69.9999MHz...

![WeChat 截圖_20241119152319](https://github.com/user-attachments/assets/7704f726-643e-4e67-b9ef-93d667cdd8b6)

So, why is this *osc_clk* 70MHz? According to the description on page 110 of Chapter 6 of UG306E:

![WeChat 截圖_20241119152929](https://github.com/user-attachments/assets/5f8ee7fe-8135-4545-8190-88c62753139a)

> **𝑓𝐶𝐿𝐾𝑂𝑈𝑇 = 𝑓𝑜𝑠𝑐/FREQ_DIV**

However, the English version of the manual does not say what the frequency of this OSC is. In the same position in the Chinese version of the manual, you can see that the frequency of this OSC is 210MHz.

![WeChat 截圖_20241119153939](https://github.com/user-attachments/assets/6234d3a0-9731-485b-b01b-3af18eee5cf7)


In this demo, FREQ_DIV is set to 3, so the *osc_clk* = 210/3=70MHz

![WeChat 截圖_20241119153318](https://github.com/user-attachments/assets/5feafd1d-56f1-41c8-ad87-ea288eb9f343)


- For the **WARN  (PR1014)**, this is because the IO used by the *external oscillator* (aka. P16 or EMCCLK) is not GCLK PIN. Generally, this warning should be ignored unless your system involves the synchronization of multiple non-source clocks.

**Comment by Semnodime** [comment]
Thanks for the explanation, this provides sufficient details for both warnings and I can now ignore them without fearing unforseen consequences.
